spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: 43824382

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8084