spring:
  datasource:
    url: jdbc:mysql://dbmysql-grupo08.cqgaxtjzrcm6.us-west-1.rds.amazonaws.com/BookingDB

    username: admin08
    password: grupete8database

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8084